#!/bin/bash
echo "Compiling Maryo..."
echo "Target: Windows i386.."
env GOOS=windows GOARCH=386 go build -o "maryo-windows-i386.exe"
echo "Target: Windows amd64.."
env GOOS=windows GOARCH=amd64 go build -o "maryo-windows-amd64.exe"
echo "Target: Linux arm.."
env GOOS=linux GOARCH=arm go build -o "maryo-linux-arm"
echo "Target: Linux arm64.."
env GOOS=linux GOARCH=arm64 go build -o "maryo-linux-arm64"
echo "Target: Linux i386.."
env GOOS=linux GOARCH=386 go build -o "maryo-linux-i386"
echo "Target: Linux amd64.."
env GOOS=linux GOARCH=amd64 go build -o "maryo-linux-amd64"
echo "Target: Darwin i386.."
env GOOS=darwin GOARCH=386 go build -o "maryo-darwin-i386"
echo "Target: Darwin amd64.."
env GOOS=darwin GOARCH=amd64 go build -o "maryo-darwin-amd64"
echo "Finished compiling Maryo for 3 OSes across 4 different architectures!"
